<%@ page language="java" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/views/common/head.jsp"%>
    <title></title>
  	<script type="text/javascript" src="${pageContext.request.contextPath}/js/add_viewport.js"></script>
	<script type="text/javascript" src="${pageContext.request.contextPath}/js/bjTree.js"></script>
	<style type="text/css">
		.store-info{
			background:url('${pageContext.request.contextPath}/imgs/store-info.gif') left top no-repeat;
		}
		body{
			font-size:12px;
		}
	</style>
	<script type="text/javascript">
		Ext.onReady(function(){
			new Ext.QuickTips.init();//提示信息加载
			var mainFrame = new MianFrame();
			setNavigate("人事管理 >> 职工管理 >> 添加职工信息","本页面提供添加职工信息功能");
			var editForm = new Ext.FormPanel({
				layout:'column',
				width:700,
				bodyStyle:'padding:10px',
				border:false,
				defaults:{
					border:false,
					labelAlign:'right',
					columnWidth:.5,
					defaultType:'textfield',
					layout:'form',
					labelWidth:110,
					defaults:{
						anchor:'95%'
					}
				},
				items:[
					{
						items:[
							{
								name:'rybh',
								emptyText:'必填',
								allowBlank:false,
								fieldLabel:'人员编号',
								listeners:{
									"blur":function(){
									}
								}
							},{
								name:'ryxm',
								emptyText:'必填',
								allowBlank:false,
								fieldLabel:'人员姓名',
								id:'txtRyxm'
							},{
								hiddenName:'member.role.depart.depid',
								emptyText:'必填',
								allowBlank:false,
								fieldLabel:'部门',
								xtype:'combo',
								readOnly:true,
								triggerAction:'all',
								displayField:"name",
								valueField:'depid',
								store:new Ext.data.JsonStore({
									url:contextPath+'/rsgl/bmglAction.do?method=getAllBmForList',
									fields:["depid","name"]
								}),
								listeners:{
									'select':function(cob,r,ind){
										Ext.apply(Ext.getCmp('cmbRole').getStore().baseParams,{
											depid:r.get('depid')
										});
										Ext.getCmp('cmbRole').getStore().reload();
									}
								}
							},{
								hiddenName:'xb',
								emptyText:'必填',
								allowBlank:false,
								fieldLabel:'性别',
								xtype:'combo',
								mode:'local',
								readOnly:true,
								triggerAction:'all',
								displayField:"sname",
								valueField:'sid',
								store:new Ext.data.JsonStore({
									data:[{sid:"1",sname:'男'},{sid:"0",sname:'女'}],
									fields:["sid","sname"]
								})
							},{
								name:'csrq',
								fieldLabel:'出生日期',
								xtype:'datefield',
								format : 'Y-m-d'
							},{
								name:'gjdm',
								fieldLabel:'国籍',
								xtype:'combo',
								triggerAction:'all',
								displayField:"dmmc",
								valueField:'id',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=GJDM',
									fields:["id","dmmc"]
								})
							},{
								fieldLabel:'籍贯',
								name:'jg',
								xtype:'combo',
								readOnly:true,
								triggerAction:'all',
								displayField:"dmmc",
								valueField:'id',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=JGDM',
									fields:["id","dmmc"]
								})
							},{
								name:'csd',
								fieldLabel:'出生地',
								xtype:'combo',
								triggerAction:'all',
								displayField:"dmmc",
								valueField:'id',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=JGDM',
									fields:["id","dmmc"]
								})
							},{
								fieldLabel:'政治面貌',
								hiddenName:'zzmm',
								readOnly:true,
								xtype:'combo',
								triggerAction:'all',
								displayField:"dmmc",
								valueField:'lxdm',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=ZZMMDM',
									fields:["lxdm","dmmc"]
								})
							},{
								fieldLabel:'入党(团)时间',
								name:'ryhrdsj',
								xtype:'datefield',
								format:'Y-m-d'
							},{
								name:'mzdm',
								fieldLabel:'民族',
								xtype:'combo',
								readOnly:true,
								triggerAction:'all',
								displayField:"dmmc",
								valueField:'id',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=MZDM',
									fields:["id","dmmc"]
								})
							},{
								fieldLabel:'参加工作时间',
								name:'cjgzsj',
								xtype:'datefield',
								format:'Y-m-d'
							},{
								fieldLabel:'职务等级',
								hiddenName:'zwdjdm',
								xtype:'combo',
								readOnly:true,
								triggerAction:'all',
								displayField:"dmmc",
								valueField:'lxdm',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=ZWDJDM',
									fields:["lxdm","dmmc"]
								})
							},{
								fieldLabel:'职务等级批准时间',
								name:'zwdjpzsj',
								xtype:'datefield',
								format:'Y-m-d'
							},{
								fieldLabel:'专业技术资格等级',
								hiddenName:'zgdjhdsj',
								readOnly:true,
								xtype:'combo',
								triggerAction:'all',
								displayField:"dmmc",
								valueField:'lxdm',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=ZYJSZGDJDM',
									fields:["lxdm","dmmc"]
								})
							},{
								fieldLabel:'资格等级获得时间',
								name:'zgdjhqsj',
								xtype:'datefield',
								format:'Y-m-d'
							},{
								fieldLabel:'工勤人员技术等级',
								hiddenName:'gqryjsdjdm',
								xtype:'combo',
								readOnly:true,
								triggerAction:'all',
								displayField:"dmmc",
								valueField:'lxdm',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=GQRYDJDM',
									fields:["lxdm","dmmc"]
								})
							},{
								fieldLabel:'技术等级获得时间',
								name:'jsdjhdsj',
								xtype:'datefield',
								format:'Y-m-d'
							}
						]
					},{
						items:[
							{
								fieldLabel:'岗位',
								name:'gw'
							},{
								fieldLabel:'身份证号',
								name:'sfzh'
							},
							{
								id:'cmbRole',
								hiddenName:'member.role.rolid',
								emptyText:'必填',
								allowBlank:false,
								fieldLabel:'职务',
								xtype:'combo',
								mode:'local',
								readOnly:true,
								triggerAction:'all',
								displayField:"name",
								valueField:'rolid',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/zwglAction.do?method=getRolByDepart',
									fields:["rolid","name"]
								})
							},
							{
								fieldLabel:'办公室电话',
								name:'bgsdh'
							},{
								fieldLabel:'手机号码',
								name:'sjhm'
							},{
								fieldLabel:'入职时间',
								name:'rzsj',
								allowBlank:false,
								emptyText:'必填',
								xtype:'datefield',
								format : 'Y-m-d'
							},{
								fieldLabel:'转职时间',
								name:'zzsj',
								xtype:'datefield',
								format : 'Y-m-d'
							},{
								fieldLabel:'离职时间',
								name:'lzsj',
								xtype:'datefield',
								format : 'Y-m-d'
							},{
								fieldLabel:'在职状态',
								hiddenName:'zt',
								xtype:'combo',
								allowBlank:false,
								emptyText:'必填',
								mode:'local',
								readOnly:true,
								triggerAction:'all',
								displayField:"sname",
								valueField:'sid',
								store:new Ext.data.JsonStore({
									data:[{sid:"1",sname:'在职'},{sid:"0",sname:'离职'}],
									fields:["sid","sname"]
								})
							},{
								fieldLabel:'人员类别',
								name:'rylbdm',
								xtype:'combo',
								readOnly:true,
								triggerAction:'all',
								displayField:"dmmc",
								valueField:'lxdm',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=RYLBDM',
									fields:["lxdm","dmmc"]
								})
							},{
								fieldLabel:'健康状况',
								name:'jkqkdm',
								readOnly:true,
								xtype:'combo',
								triggerAction:'all',
								displayField:"dmmc",
								valueField:'id',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=JKZKDM',
									fields:["id","dmmc"]
								})
							},{
								fieldLabel:'婚姻状况',
								name:'hyqk',
								xtype:'combo',
								triggerAction:'all',
								readOnly:true,
								displayField:"dmmc",
								valueField:'id',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=HYQKDM',
									fields:["id","dmmc"]
								})
							},{
								fieldLabel:'血型',
								name:'xx',
								xtype:'combo',
								readOnly:true,
								triggerAction:'all',
								displayField:"dmmc",
								valueField:'id',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=XXDM',
									fields:["id","dmmc"]
								})
							},{
								fieldLabel:'文化程度',
								hiddenName:'whcddm',
								xtype:'combo',
								readOnly:true,
								triggerAction:'all',
								displayField:"dmmc",
								valueField:'lxdm',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=WHCDDM',
									fields:["lxdm","dmmc"]
								})
							},{
								fieldLabel:'家庭出生',
								name:'jtcsdm',
								readOnly:true,
								xtype:'combo',
								triggerAction:'all',
								displayField:"dmmc",
								valueField:'id',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=JTCSDM',
									fields:["id","dmmc"]
								})
							},{
								fieldLabel:'毕业院校',
								name:'byyx'
							},{
								fieldLabel:'专业与学制',
								name:'zyyxz'
							},{
								fieldLabel:'学位',
								name:'xwdm',
								xtype:'combo',
								readOnly:true,
								triggerAction:'all',
								displayField:"dmmc",
								valueField:'lxdm',
								store:new Ext.data.JsonStore({
									url:contextPath+'/system/lxdmglAction.do?method=getLxdmBySjjc&dmjc=XWDM',
									fields:["lxdm","dmmc"]
								})
							}
						]
					},{
						columnWidth:1,
						layout:'form',
						labelWidth:110,
						defaults:{
							anchor:'97.5%'	
						},
						items:[
							{
								fieldLabel:'备注',
								name:'bz',
								xtype:'textarea',
								height:80
							},
							{
								xtype:'panel',
								layout:'column',
								border:false,
								items:[
								{
									columnWidth:0.14,
									xtype:'label',
									text:'是否为该职工生成系统用户:',
									style:'text-valign:middle;'
								},{
										columnWidth:0.1,
										xtype:'checkbox',
										handler:function(chk,checked){
											if(checked)
											{
												Ext.getCmp('labUsername').show();
												Ext.getCmp('labPassword').show();
												Ext.getCmp('txtUsername').show();
												Ext.getCmp('txtPassword').show();
											}else
											{
												Ext.getCmp('txtUsername').setValue('');
												Ext.getCmp('txtPassword').setValue('');
												Ext.getCmp('txtUsername').hide();
												Ext.getCmp('txtPassword').hide();
												Ext.getCmp('labUsername').hide();
												Ext.getCmp('labPassword').hide();
											}
										}
									},
									{
										xtype:'label',
										columnWidth:0.1,
										text:'登录帐号:',
										id:'labUsername',
										hidden:true
									}
									,{
										columnWidth:0.2,
										id:'txtUsername',
										name:'member.loginid',
										xtype:'textfield',
										hidden:true
									},
									{
										xtype:'label',
										columnWidth:0.1,
										text:'登录密码:',
										id:'labPassword',
										hidden:true
									},{
										columnWidth:0.2,
										id:'txtPassword',
										inputType:'password',
										name:'member.password',
										xtype:'textfield',
										hidden:true
									}
								]
							},{
								xtype:'panel',
								layout:'column',
								border:false,
								items:[
									{
										xtype:'label',
										columnWidth:.14,
										text:'是否为老师:'
									},
									{
										name:'isTeacher',
										columnWidth:0.1,
										xtype:'checkbox',
										handler: function(chk, checked){
											if (checked) {
												Ext.getCmp('hidLs').setValue(Ext.getCmp('txtRyxm').getValue());
											}
										}
									},
									{
										xtype:'hidden',
										name:'ls.ls',
										id:'hidLs'
									}
								]
							},
							{
								xtype:'panel',
								id:'panBzr',
								layout:'column',
								border:false,
								listeners:{
									'afterrender':function(p)
									{
										Ext.getCmp('selectTreebjName').hide();
										Ext.getCmp('labBjxx').hide();
									}
								},
								items:[
									{
										xtype:'label',
										columnWidth:.14,
										text:'是否为班主任:'
									},
									{
										name:'isBzr',
										columnWidth:0.1,
										xtype:'checkbox',
										handler: function(chk, checked){
											if (checked) {
												Ext.getCmp('hidBzr').setValue(Ext.getCmp('txtRyxm').getValue());
												Ext.getCmp('labBjxx').show();
												Ext.getCmp('selectTreebjName').show();
											}
											else
											{
												Ext.getCmp('hidBzr').setValue('');
												Ext.getCmp('labBjxx').hide();
												Ext.getCmp('selectTreebjName').hide();
											}
										}
									},
									{
										xtype:'hidden',
										name:'bzr.bzrxm',
										id:'hidBzr'
									},{
										xtype:'hidden',
										id:'hidBjid',
										name:'bzr.bzrbj.bjdm.id'
									},{
										xtype:'label',
										text:'选择班主任带班班级:',
										id:'labBjxx'
									},getBjTree()
								]
							}
						]
					}
				]
			});
			Ext.getCmp('editPanel').add(editForm);
			initTbar(editForm);
			Ext.getCmp('saveBtn').on('click',function(){
				if(editForm.form.isValid()){
					editForm.form.doAction('submit',{
						url:contextPath+'/rsgl/ryglAction.do?method=addRy',
						method:'post',
						waitTitle:'提示信息',                                                    
                        waitMsg:'数据更新中，请稍候...',
                        success:function(form,action){
                        	if(action.result.success){
								Ext.Msg.confirm('操作提示','添加成功，是否继续添加？',function(btn){
									if(btn=="no"){
										history.back();
									}else{
										editForm.form.reset();
									}
								});
                        	}else{
                        		Ext.Msg.alert('添加失败', message);
                        	}
                        },
                        failure:function(){
                            Ext.Msg.alert('操作失败','服务器无法连接，请稍后重试！');
                       	}
					});
				}
			});
		});
	</script>
  </head>
  <body>
  <input type="hidden" id='qx' value='{qxlx}'>
  <table width="100%" height='100%' >
  	<tr>
  		<td align="center" valign="middle">
			<div id='loadDiv' style="font-size:12px;">
			<img width='50' height='50' src='${pageContext.request.contextPath}/imgs/login-load.gif'>
			数据加载中，请稍后 . . .
			</div>
		</td>
  	</tr>
  </table>				
  </body>
</html>
